import React, { useEffect, useRef, useState } from 'react';
import { Activity, Gauge, Play, Timer, Users, X, Zap } from 'lucide-react';
import { useAppStore } from '../../store/appStore.js';

interface StressModalProps { isOpen: boolean; onClose: () => void; }

export const StressModal: React.FC<StressModalProps> = ({ isOpen, onClose }) => {
  const { activeSession, runK6Stress, isRunning } = useAppStore();
  const [targetRps, setTargetRps] = useState(''); const [durationSec, setDurationSec] = useState(''); const [maxVus, setMaxVus] = useState('');
  const dialogRef = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!isOpen) return; const previous = document.activeElement as HTMLElement | null; const getFocusable = () => Array.from(dialogRef.current?.querySelectorAll<HTMLElement>('input, select, textarea, button, [href], [tabindex]:not([tabindex="-1"])') ?? []).filter((element) => !element.hasAttribute('disabled')); getFocusable()[0]?.focus(); const onKeyDown = (event: KeyboardEvent) => { if (event.key === 'Escape') { onClose(); return; } if (event.key !== 'Tab') return; const elements = getFocusable(); if (elements.length === 0) return; const first = elements[0]; const last = elements[elements.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } }; document.addEventListener('keydown', onKeyDown); return () => { document.removeEventListener('keydown', onKeyDown); previous?.focus(); }; }, [isOpen, onClose]);
  if (!isOpen) return null;
  const valid = Number(targetRps) > 0 && Number(durationSec) > 0 && Number(maxVus) > 0;
  const launch = async () => { if (!valid) return; onClose(); await runK6Stress(Number(targetRps), Number(durationSec), Number(maxVus)); };
  return <div className="dialog-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><div ref={dialogRef} className="dialog-card max-w-lg" role="dialog" aria-modal="true" aria-labelledby="stress-dialog-title"><div className="flex items-center justify-between gap-3"><h2 id="stress-dialog-title" className="flex items-center gap-2 text-sm font-bold text-white"><Zap className="w-4 h-4 text-amber-400" />k6 stress configuration</h2><button type="button" onClick={onClose} className="p-1.5 text-slate-400 hover:text-white rounded hover:bg-slate-800" aria-label="Close stress dialog"><X className="w-4 h-4" /></button></div><div className="mt-4 space-y-4 text-xs"><div className="bg-slate-950 p-3 rounded-lg border border-slate-800"><div className="text-[11px] text-slate-400 mb-1 font-mono">Target session</div><div className="font-bold text-white truncate">{activeSession?.name ?? 'No session selected'}</div></div><div className="grid gap-3 sm:grid-cols-3"><label className="text-slate-300"><span className="flex items-center gap-1.5 mb-1"><Gauge className="w-3.5 h-3.5 text-amber-400" />Target RPS</span><input required type="number" min="1" value={targetRps} onChange={(event) => setTargetRps(event.target.value)} className="field w-full" /></label><label className="text-slate-300"><span className="flex items-center gap-1.5 mb-1"><Timer className="w-3.5 h-3.5 text-sky-400" />Duration seconds</span><input required type="number" min="1" value={durationSec} onChange={(event) => setDurationSec(event.target.value)} className="field w-full" /></label><label className="text-slate-300"><span className="flex items-center gap-1.5 mb-1"><Users className="w-3.5 h-3.5 text-emerald-400" />Max VUs</span><input required type="number" min="1" value={maxVus} onChange={(event) => setMaxVus(event.target.value)} className="field w-full" /></label></div><div className="bg-amber-950/30 border border-amber-800/40 p-3 rounded-lg flex items-start gap-2.5 text-amber-200/80"><Activity className="w-4 h-4 text-amber-400 shrink-0" /><p>Values are sent to the host runner only after explicit launch. The browser shell does not synthesize load metrics.</p></div></div><div className="flex justify-end gap-2 mt-5"><button type="button" onClick={onClose} className="button-muted">Cancel</button><button type="button" onClick={() => void launch()} disabled={!valid || isRunning} title={valid && !isRunning ? 'Launch the configured k6 run' : 'Enter positive values and wait for any active run to finish'} className="button-execute bg-amber-600 hover:bg-amber-500 disabled:opacity-50"><Play className="w-3.5 h-3.5 fill-current" />Launch k6</button></div></div></div>;
};
